# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - CGO_ENABLED=0
  - GO111MODULE=auto

builds:
  - id: binary
    goos:
      - windows
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.buildSource=binaryRelease

archives:
  - builds:
      - binary
    format_overrides:
      - goos: windows
        format: zip